CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(30),
    PRIMARY KEY (id)
);

CREATE TABLE `advertisements` (
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255),
    userId INT,
    PRIMARY KEY (id)
);

INSERT INTO users(name) VALUES ('Joel Callinan');
INSERT INTO users(name) VALUES ('Ronny Tancock');
INSERT INTO users(name) VALUES ('Sarine Leftridge');
INSERT INTO users(name) VALUES ('Rebecka Crock');
INSERT INTO users(name) VALUES ('Yurik Chable');
INSERT INTO users(name) VALUES ('Palm Santry');
INSERT INTO users(name) VALUES ('Abagail Poff');
INSERT INTO users(name) VALUES ('Janina Retchford');
INSERT INTO users(name) VALUES ('Launce Dionsetto');
INSERT INTO users(name) VALUES ('Matilde Jorge');
INSERT INTO users(name) VALUES ('Tirrell Hargey');
INSERT INTO users(name) VALUES ('Cristal Gilston');
INSERT INTO users(name) VALUES ('Dillie Godman');
INSERT INTO users(name) VALUES ('Corabelle Hurkett');
INSERT INTO users(name) VALUES ('Isa Huguet');
INSERT INTO users(name) VALUES ('Horatio Disbrey');
INSERT INTO users(name) VALUES ('Roanna Rosenblad');
INSERT INTO users(name) VALUES ('Sean Burleton');
INSERT INTO users(name) VALUES ('Daryl Brundall');
INSERT INTO users(name) VALUES ('Erv Colthard');
INSERT INTO users(name) VALUES ('Olympie Binnion');
INSERT INTO users(name) VALUES ('Kippy Dunsmore');
INSERT INTO users(name) VALUES ('Garrik Withnall');
INSERT INTO users(name) VALUES ('Valina Mishaw');
INSERT INTO users(name) VALUES ('Karola Nesbeth');
INSERT INTO users(name) VALUES ('Lorin Vigietti');
INSERT INTO users(name) VALUES ('Aviva Soar');
INSERT INTO users(name) VALUES ('Lonnie Stallan');
INSERT INTO users(name) VALUES ('Callida Chattock');
INSERT INTO users(name) VALUES ('Augustin Mengo');
INSERT INTO users(name) VALUES ('Erma Beeho');
INSERT INTO users(name) VALUES ('Kory Argont');
INSERT INTO users(name) VALUES ('Killie Darben');
INSERT INTO users(name) VALUES ('Junie Crees');
INSERT INTO users(name) VALUES ('Chrystel Rizon');
INSERT INTO users(name) VALUES ('Dominic Folks');
INSERT INTO users(name) VALUES ('Todd Watkinson');
INSERT INTO users(name) VALUES ('Nanon Mottley');
INSERT INTO users(name) VALUES ('Myriam Pendre');
INSERT INTO users(name) VALUES ('Rouvin Lowen');
INSERT INTO users(name) VALUES ('Gamaliel Keller');
INSERT INTO users(name) VALUES ('Lyon Antognetti');
INSERT INTO users(name) VALUES ('Shela McGarrity');
INSERT INTO users(name) VALUES ('Tressa McLellan');
INSERT INTO users(name) VALUES ('Shelli Jeremiah');
INSERT INTO users(name) VALUES ('Barnebas Andreini');
INSERT INTO users(name) VALUES ('Adolpho Grzes');
INSERT INTO users(name) VALUES ('Celesta Mayoral');
INSERT INTO users(name) VALUES ('Bernhard Kegley');
INSERT INTO users(name) VALUES ('Ivan Escoffier');
INSERT INTO users(name) VALUES ('Johnnie Reimers');
INSERT INTO users(name) VALUES ('Ladonna Baselli');
INSERT INTO users(name) VALUES ('Ronica Jeves');
INSERT INTO users(name) VALUES ('Sigismondo Semorad');
INSERT INTO users(name) VALUES ('Kerrie Upex');
INSERT INTO users(name) VALUES ('Hieronymus Tomaszewski');
INSERT INTO users(name) VALUES ('Odo Sandifer');
INSERT INTO users(name) VALUES ('Noble Yakuntzov');
INSERT INTO users(name) VALUES ('Georgy Carine');
INSERT INTO users(name) VALUES ('Wake Izakson');
INSERT INTO users(name) VALUES ('Vassily Dyment');
INSERT INTO users(name) VALUES ('Mimi Benettelli');
INSERT INTO users(name) VALUES ('Lorilee Pringour');
INSERT INTO users(name) VALUES ('Alicia Aspin');
INSERT INTO users(name) VALUES ('Nester Naulls');
INSERT INTO users(name) VALUES ('Vaughn Sidgwick');
INSERT INTO users(name) VALUES ('Corly Beese');
INSERT INTO users(name) VALUES ('Chelsae Hub');
INSERT INTO users(name) VALUES ('Pippo Denley');
INSERT INTO users(name) VALUES ('Chaddy Fernihough');
INSERT INTO users(name) VALUES ('Bartlet Mollitt');
INSERT INTO users(name) VALUES ('Phebe Rubinow');
INSERT INTO users(name) VALUES ('Sully Biaggiotti');
INSERT INTO users(name) VALUES ('Horten Navarro');
INSERT INTO users(name) VALUES ('Miner Smy');
INSERT INTO users(name) VALUES ('Teri Tocher');
INSERT INTO users(name) VALUES ('Edik Cavendish');
INSERT INTO users(name) VALUES ('Leyla Blitz');
INSERT INTO users(name) VALUES ('Ianthe Sekulla');
INSERT INTO users(name) VALUES ('Norbert Laimable');
INSERT INTO users(name) VALUES ('Glynda Buckler');
INSERT INTO users(name) VALUES ('Corliss Izod');
INSERT INTO users(name) VALUES ('Kamilah Barck');
INSERT INTO users(name) VALUES ('Midge Muckart');
INSERT INTO users(name) VALUES ('Ronnie Boyne');
INSERT INTO users(name) VALUES ('Amaleta Sturgess');
INSERT INTO users(name) VALUES ('Brooke Vido');
INSERT INTO users(name) VALUES ('Benedicta Di Napoli');
INSERT INTO users(name) VALUES ('Nikos Bulger');
INSERT INTO users(name) VALUES ('Khalil Chevins');
INSERT INTO users(name) VALUES ('Davida Musterd');
INSERT INTO users(name) VALUES ('Aubree Farryann');
INSERT INTO users(name) VALUES ('Laraine Fraulo');
INSERT INTO users(name) VALUES ('Antonie Karlsson');
INSERT INTO users(name) VALUES ('Rinaldo Skocroft');
INSERT INTO users(name) VALUES ('Edlin Tonkin');
INSERT INTO users(name) VALUES ('Lanae Banbury');
INSERT INTO users(name) VALUES ('Florencia Duckitt');
INSERT INTO users(name) VALUES ('Dannye Shyre');

insert into advertisements (title, userId) values ('Executive Secretary', null);
insert into advertisements (title, userId) values ('Geologist II', null);
insert into advertisements (title, userId) values ('VP Marketing', null);
insert into advertisements (title, userId) values ('Database Administrator I', null);
insert into advertisements (title, userId) values ('Research Associate', null);
insert into advertisements (title, userId) values ('Librarian', null);
insert into advertisements (title, userId) values ('Nurse', null);
insert into advertisements (title, userId) values ('Graphic Designer', null);
insert into advertisements (title, userId) values ('Administrative Assistant II', 77);
insert into advertisements (title, userId) values ('General Manager', null);
insert into advertisements (title, userId) values ('Nurse', 54);
insert into advertisements (title, userId) values ('Desktop Support Technician', 32);
insert into advertisements (title, userId) values ('Structural Engineer', 45);
insert into advertisements (title, userId) values ('Assistant Professor', 4);
insert into advertisements (title, userId) values ('Database Administrator II', null);
insert into advertisements (title, userId) values ('VP Marketing', 25);
insert into advertisements (title, userId) values ('Marketing Assistant', 39);
insert into advertisements (title, userId) values ('Community Outreach Specialist', 93);
insert into advertisements (title, userId) values ('Staff Accountant I', 98);
insert into advertisements (title, userId) values ('Information Systems Manager', 10);
insert into advertisements (title, userId) values ('Actuary', null);
insert into advertisements (title, userId) values ('Structural Engineer', 89);
insert into advertisements (title, userId) values ('VP Accounting', 9);
insert into advertisements (title, userId) values ('Junior Executive', 21);
insert into advertisements (title, userId) values ('Financial Advisor', null);
insert into advertisements (title, userId) values ('Internal Auditor', 6);
insert into advertisements (title, userId) values ('Software Engineer III', 95);
insert into advertisements (title, userId) values ('Staff Scientist', null);
insert into advertisements (title, userId) values ('Chief Design Engineer', 82);
insert into advertisements (title, userId) values ('GIS Technical Architect', 87);
insert into advertisements (title, userId) values ('Research Nurse', null);
insert into advertisements (title, userId) values ('Senior Sales Associate', null);
insert into advertisements (title, userId) values ('Legal Assistant', 80);
insert into advertisements (title, userId) values ('Executive Secretary', 17);
insert into advertisements (title, userId) values ('Graphic Designer', 99);
insert into advertisements (title, userId) values ('Dental Hygienist', 36);
insert into advertisements (title, userId) values ('Physical Therapy Assistant', 9);
insert into advertisements (title, userId) values ('Software Test Engineer III', null);
insert into advertisements (title, userId) values ('General Manager', 92);
insert into advertisements (title, userId) values ('Social Worker', null);
insert into advertisements (title, userId) values ('Clinical Specialist', 52);
insert into advertisements (title, userId) values ('Graphic Designer', 96);
insert into advertisements (title, userId) values ('Safety Technician I', 38);
insert into advertisements (title, userId) values ('Internal Auditor', null);
insert into advertisements (title, userId) values ('Financial Analyst', null);
insert into advertisements (title, userId) values ('Registered Nurse', 43);
insert into advertisements (title, userId) values ('Help Desk Operator', 96);
insert into advertisements (title, userId) values ('Desktop Support Technician', 79);
insert into advertisements (title, userId) values ('Administrative Assistant IV', null);
insert into advertisements (title, userId) values ('Teacher', null);
insert into advertisements (title, userId) values ('Environmental Tech', 1);
insert into advertisements (title, userId) values ('Librarian', 67);
insert into advertisements (title, userId) values ('Quality Control Specialist', null);
insert into advertisements (title, userId) values ('Financial Analyst', null);
insert into advertisements (title, userId) values ('Web Designer II', 58);
insert into advertisements (title, userId) values ('Nurse', 92);
insert into advertisements (title, userId) values ('Account Executive', 60);
insert into advertisements (title, userId) values ('Quality Engineer', null);
insert into advertisements (title, userId) values ('Physical Therapy Assistant', null);
insert into advertisements (title, userId) values ('Administrative Assistant II', 44);
insert into advertisements (title, userId) values ('Administrative Officer', 47);
insert into advertisements (title, userId) values ('Account Executive', 94);
insert into advertisements (title, userId) values ('Accounting Assistant II', 52);
insert into advertisements (title, userId) values ('Quality Engineer', null);
insert into advertisements (title, userId) values ('Human Resources Manager', null);
insert into advertisements (title, userId) values ('Developer I', null);
insert into advertisements (title, userId) values ('Budget/Accounting Analyst II', 25);
insert into advertisements (title, userId) values ('Nurse Practicioner', 75);
insert into advertisements (title, userId) values ('Dental Hygienist', 58);
insert into advertisements (title, userId) values ('Senior Cost Accountant', null);
insert into advertisements (title, userId) values ('Help Desk Technician', null);
insert into advertisements (title, userId) values ('Senior Developer', null);
insert into advertisements (title, userId) values ('Design Engineer', 87);
insert into advertisements (title, userId) values ('Analyst Programmer', null);
insert into advertisements (title, userId) values ('Civil Engineer', 23);
insert into advertisements (title, userId) values ('Statistician IV', null);
insert into advertisements (title, userId) values ('Account Coordinator', 81);
insert into advertisements (title, userId) values ('Physical Therapy Assistant', 97);
insert into advertisements (title, userId) values ('Social Worker', 45);
insert into advertisements (title, userId) values ('Clinical Specialist', 67);
insert into advertisements (title, userId) values ('Account Coordinator', null);
insert into advertisements (title, userId) values ('Business Systems Development Analyst', 76);
insert into advertisements (title, userId) values ('Mechanical Systems Engineer', 14);
insert into advertisements (title, userId) values ('Safety Technician I', 61);
insert into advertisements (title, userId) values ('Engineer III', 81);
insert into advertisements (title, userId) values ('Research Associate', 99);
insert into advertisements (title, userId) values ('Help Desk Technician', 73);
insert into advertisements (title, userId) values ('Engineer I', 54);
insert into advertisements (title, userId) values ('Professor', null);
insert into advertisements (title, userId) values ('Payment Adjustment Coordinator', null);
insert into advertisements (title, userId) values ('Teacher', null);
insert into advertisements (title, userId) values ('Programmer I', 20);
insert into advertisements (title, userId) values ('Business Systems Development Analyst', null);
insert into advertisements (title, userId) values ('Software Test Engineer II', 47);
insert into advertisements (title, userId) values ('Administrative Assistant III', null);
insert into advertisements (title, userId) values ('Recruiting Manager', null);
insert into advertisements (title, userId) values ('Paralegal', null);
insert into advertisements (title, userId) values ('Physical Therapy Assistant', null);
insert into advertisements (title, userId) values ('Chief Design Engineer', 80);
insert into advertisements (title, userId) values ('Recruiter', 63);