-- Users table creation
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
);

-- Advertisements table creation
CREATE TABLE `advertisements` (
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    userId INT,
    PRIMARY KEY (id),
    FOREIGN KEY (userId) REFERENCES users(id)
);

-- Users demo data
INSERT INTO users(name) VALUES ('Joel Callinan');
INSERT INTO users(name) VALUES ('Ronny Tancock');
INSERT INTO users(name) VALUES ('Sarine Leftridge');
INSERT INTO users(name) VALUES ('Rebecka Crock');
INSERT INTO users(name) VALUES ('Yurik Chable');
INSERT INTO users(name) VALUES ('Palm Santry');
INSERT INTO users(name) VALUES ('Abagail Poff');
INSERT INTO users(name) VALUES ('Janina Retchford');
INSERT INTO users(name) VALUES ('Launce Dionsetto');
INSERT INTO users(name) VALUES ('Matilde Jorge');
INSERT INTO users(name) VALUES ('Tirrell Hargey');
INSERT INTO users(name) VALUES ('Cristal Gilston');
INSERT INTO users(name) VALUES ('Dillie Godman');
INSERT INTO users(name) VALUES ('Corabelle Hurkett');
INSERT INTO users(name) VALUES ('Isa Huguet');
INSERT INTO users(name) VALUES ('Horatio Disbrey');
INSERT INTO users(name) VALUES ('Roanna Rosenblad');
INSERT INTO users(name) VALUES ('Sean Burleton');
INSERT INTO users(name) VALUES ('Daryl Brundall');
INSERT INTO users(name) VALUES ('Erv Colthard');
INSERT INTO users(name) VALUES ('Olympie Binnion');
INSERT INTO users(name) VALUES ('Kippy Dunsmore');
INSERT INTO users(name) VALUES ('Garrik Withnall');
INSERT INTO users(name) VALUES ('Valina Mishaw');
INSERT INTO users(name) VALUES ('Karola Nesbeth');
INSERT INTO users(name) VALUES ('Lorin Vigietti');
INSERT INTO users(name) VALUES ('Aviva Soar');
INSERT INTO users(name) VALUES ('Lonnie Stallan');
INSERT INTO users(name) VALUES ('Callida Chattock');
INSERT INTO users(name) VALUES ('Augustin Mengo');
INSERT INTO users(name) VALUES ('Erma Beeho');
INSERT INTO users(name) VALUES ('Kory Argont');
INSERT INTO users(name) VALUES ('Killie Darben');
INSERT INTO users(name) VALUES ('Junie Crees');
INSERT INTO users(name) VALUES ('Chrystel Rizon');
INSERT INTO users(name) VALUES ('Dominic Folks');
INSERT INTO users(name) VALUES ('Todd Watkinson');
INSERT INTO users(name) VALUES ('Nanon Mottley');
INSERT INTO users(name) VALUES ('Myriam Pendre');
INSERT INTO users(name) VALUES ('Rouvin Lowen');
INSERT INTO users(name) VALUES ('Gamaliel Keller');
INSERT INTO users(name) VALUES ('Lyon Antognetti');
INSERT INTO users(name) VALUES ('Shela McGarrity');
INSERT INTO users(name) VALUES ('Tressa McLellan');
INSERT INTO users(name) VALUES ('Shelli Jeremiah');
INSERT INTO users(name) VALUES ('Barnebas Andreini');
INSERT INTO users(name) VALUES ('Adolpho Grzes');
INSERT INTO users(name) VALUES ('Celesta Mayoral');
INSERT INTO users(name) VALUES ('Bernhard Kegley');
INSERT INTO users(name) VALUES ('Ivan Escoffier');
INSERT INTO users(name) VALUES ('Johnnie Reimers');
INSERT INTO users(name) VALUES ('Ladonna Baselli');
INSERT INTO users(name) VALUES ('Ronica Jeves');
INSERT INTO users(name) VALUES ('Sigismondo Semorad');
INSERT INTO users(name) VALUES ('Kerrie Upex');
INSERT INTO users(name) VALUES ('Hieronymus Tomaszewski');
INSERT INTO users(name) VALUES ('Odo Sandifer');
INSERT INTO users(name) VALUES ('Noble Yakuntzov');
INSERT INTO users(name) VALUES ('Georgy Carine');
INSERT INTO users(name) VALUES ('Wake Izakson');
INSERT INTO users(name) VALUES ('Vassily Dyment');
INSERT INTO users(name) VALUES ('Mimi Benettelli');
INSERT INTO users(name) VALUES ('Lorilee Pringour');
INSERT INTO users(name) VALUES ('Alicia Aspin');
INSERT INTO users(name) VALUES ('Nester Naulls');
INSERT INTO users(name) VALUES ('Vaughn Sidgwick');
INSERT INTO users(name) VALUES ('Corly Beese');
INSERT INTO users(name) VALUES ('Chelsae Hub');
INSERT INTO users(name) VALUES ('Pippo Denley');
INSERT INTO users(name) VALUES ('Chaddy Fernihough');
INSERT INTO users(name) VALUES ('Bartlet Mollitt');
INSERT INTO users(name) VALUES ('Phebe Rubinow');
INSERT INTO users(name) VALUES ('Sully Biaggiotti');
INSERT INTO users(name) VALUES ('Horten Navarro');
INSERT INTO users(name) VALUES ('Miner Smy');
INSERT INTO users(name) VALUES ('Teri Tocher');
INSERT INTO users(name) VALUES ('Edik Cavendish');
INSERT INTO users(name) VALUES ('Leyla Blitz');
INSERT INTO users(name) VALUES ('Ianthe Sekulla');
INSERT INTO users(name) VALUES ('Norbert Laimable');
INSERT INTO users(name) VALUES ('Glynda Buckler');
INSERT INTO users(name) VALUES ('Corliss Izod');
INSERT INTO users(name) VALUES ('Kamilah Barck');
INSERT INTO users(name) VALUES ('Midge Muckart');
INSERT INTO users(name) VALUES ('Ronnie Boyne');
INSERT INTO users(name) VALUES ('Amaleta Sturgess');
INSERT INTO users(name) VALUES ('Brooke Vido');
INSERT INTO users(name) VALUES ('Benedicta Di Napoli');
INSERT INTO users(name) VALUES ('Nikos Bulger');
INSERT INTO users(name) VALUES ('Khalil Chevins');
INSERT INTO users(name) VALUES ('Davida Musterd');
INSERT INTO users(name) VALUES ('Aubree Farryann');
INSERT INTO users(name) VALUES ('Laraine Fraulo');
INSERT INTO users(name) VALUES ('Antonie Karlsson');
INSERT INTO users(name) VALUES ('Rinaldo Skocroft');
INSERT INTO users(name) VALUES ('Edlin Tonkin');
INSERT INTO users(name) VALUES ('Lanae Banbury');
INSERT INTO users(name) VALUES ('Florencia Duckitt');
INSERT INTO users(name) VALUES ('Dannye Shyre');

-- Advertisements demo data
INSERT INTO advertisements(title, userId) VALUES ('Executive Secretary', null);
INSERT INTO advertisements(title, userId) VALUES ('Geologist II', null);
INSERT INTO advertisements(title, userId) VALUES ('VP Marketing', null);
INSERT INTO advertisements(title, userId) VALUES ('Database Administrator I', null);
INSERT INTO advertisements(title, userId) VALUES ('Research Associate', null);
INSERT INTO advertisements(title, userId) VALUES ('Librarian', null);
INSERT INTO advertisements(title, userId) VALUES ('Nurse', null);
INSERT INTO advertisements(title, userId) VALUES ('Graphic Designer', null);
INSERT INTO advertisements(title, userId) VALUES ('Administrative Assistant II', 77);
INSERT INTO advertisements(title, userId) VALUES ('General Manager', null);
INSERT INTO advertisements(title, userId) VALUES ('Nurse', 54);
INSERT INTO advertisements(title, userId) VALUES ('Desktop Support Technician', 32);
INSERT INTO advertisements(title, userId) VALUES ('Structural Engineer', 45);
INSERT INTO advertisements(title, userId) VALUES ('Assistant Professor', 4);
INSERT INTO advertisements(title, userId) VALUES ('Database Administrator II', null);
INSERT INTO advertisements(title, userId) VALUES ('VP Marketing', 25);
INSERT INTO advertisements(title, userId) VALUES ('Marketing Assistant', 39);
INSERT INTO advertisements(title, userId) VALUES ('Community Outreach Specialist', 93);
INSERT INTO advertisements(title, userId) VALUES ('Staff Accountant I', 98);
INSERT INTO advertisements(title, userId) VALUES ('Information Systems Manager', 10);
INSERT INTO advertisements(title, userId) VALUES ('Actuary', null);
INSERT INTO advertisements(title, userId) VALUES ('Structural Engineer', 89);
INSERT INTO advertisements(title, userId) VALUES ('VP Accounting', 9);
INSERT INTO advertisements(title, userId) VALUES ('Junior Executive', 21);
INSERT INTO advertisements(title, userId) VALUES ('Financial Advisor', null);
INSERT INTO advertisements(title, userId) VALUES ('Internal Auditor', 6);
INSERT INTO advertisements(title, userId) VALUES ('Software Engineer III', 95);
INSERT INTO advertisements(title, userId) VALUES ('Staff Scientist', null);
INSERT INTO advertisements(title, userId) VALUES ('Chief Design Engineer', 82);
INSERT INTO advertisements(title, userId) VALUES ('GIS Technical Architect', 87);
INSERT INTO advertisements(title, userId) VALUES ('Research Nurse', null);
INSERT INTO advertisements(title, userId) VALUES ('Senior Sales Associate', null);
INSERT INTO advertisements(title, userId) VALUES ('Legal Assistant', 80);
INSERT INTO advertisements(title, userId) VALUES ('Executive Secretary', 17);
INSERT INTO advertisements(title, userId) VALUES ('Graphic Designer', 99);
INSERT INTO advertisements(title, userId) VALUES ('Dental Hygienist', 36);
INSERT INTO advertisements(title, userId) VALUES ('Physical Therapy Assistant', 9);
INSERT INTO advertisements(title, userId) VALUES ('Software Test Engineer III', null);
INSERT INTO advertisements(title, userId) VALUES ('General Manager', 92);
INSERT INTO advertisements(title, userId) VALUES ('Social Worker', null);
INSERT INTO advertisements(title, userId) VALUES ('Clinical Specialist', 52);
INSERT INTO advertisements(title, userId) VALUES ('Graphic Designer', 96);
INSERT INTO advertisements(title, userId) VALUES ('Safety Technician I', 38);
INSERT INTO advertisements(title, userId) VALUES ('Internal Auditor', null);
INSERT INTO advertisements(title, userId) VALUES ('Financial Analyst', null);
INSERT INTO advertisements(title, userId) VALUES ('Registered Nurse', 43);
INSERT INTO advertisements(title, userId) VALUES ('Help Desk Operator', 96);
INSERT INTO advertisements(title, userId) VALUES ('Desktop Support Technician', 79);
INSERT INTO advertisements(title, userId) VALUES ('Administrative Assistant IV', null);
INSERT INTO advertisements(title, userId) VALUES ('Teacher', null);
INSERT INTO advertisements(title, userId) VALUES ('Environmental Tech', 1);
INSERT INTO advertisements(title, userId) VALUES ('Librarian', 67);
INSERT INTO advertisements(title, userId) VALUES ('Quality Control Specialist', null);
INSERT INTO advertisements(title, userId) VALUES ('Financial Analyst', null);
INSERT INTO advertisements(title, userId) VALUES ('Web Designer II', 58);
INSERT INTO advertisements(title, userId) VALUES ('Nurse', 92);
INSERT INTO advertisements(title, userId) VALUES ('Account Executive', 60);
INSERT INTO advertisements(title, userId) VALUES ('Quality Engineer', null);
INSERT INTO advertisements(title, userId) VALUES ('Physical Therapy Assistant', null);
INSERT INTO advertisements(title, userId) VALUES ('Administrative Assistant II', 44);
INSERT INTO advertisements(title, userId) VALUES ('Administrative Officer', 47);
INSERT INTO advertisements(title, userId) VALUES ('Account Executive', 94);
INSERT INTO advertisements(title, userId) VALUES ('Accounting Assistant II', 52);
INSERT INTO advertisements(title, userId) VALUES ('Quality Engineer', null);
INSERT INTO advertisements(title, userId) VALUES ('Human Resources Manager', null);
INSERT INTO advertisements(title, userId) VALUES ('Developer I', null);
INSERT INTO advertisements(title, userId) VALUES ('Budget/Accounting Analyst II', 25);
INSERT INTO advertisements(title, userId) VALUES ('Nurse Practicioner', 75);
INSERT INTO advertisements(title, userId) VALUES ('Dental Hygienist', 58);
INSERT INTO advertisements(title, userId) VALUES ('Senior Cost Accountant', null);
INSERT INTO advertisements(title, userId) VALUES ('Help Desk Technician', null);
INSERT INTO advertisements(title, userId) VALUES ('Senior Developer', null);
INSERT INTO advertisements(title, userId) VALUES ('Design Engineer', 87);
INSERT INTO advertisements(title, userId) VALUES ('Analyst Programmer', null);
INSERT INTO advertisements(title, userId) VALUES ('Civil Engineer', 23);
INSERT INTO advertisements(title, userId) VALUES ('Statistician IV', null);
INSERT INTO advertisements(title, userId) VALUES ('Account Coordinator', 81);
INSERT INTO advertisements(title, userId) VALUES ('Physical Therapy Assistant', 97);
INSERT INTO advertisements(title, userId) VALUES ('Social Worker', 45);
INSERT INTO advertisements(title, userId) VALUES ('Clinical Specialist', 67);
INSERT INTO advertisements(title, userId) VALUES ('Account Coordinator', null);
INSERT INTO advertisements(title, userId) VALUES ('Business Systems Development Analyst', 76);
INSERT INTO advertisements(title, userId) VALUES ('Mechanical Systems Engineer', 14);
INSERT INTO advertisements(title, userId) VALUES ('Safety Technician I', 61);
INSERT INTO advertisements(title, userId) VALUES ('Engineer III', 81);
INSERT INTO advertisements(title, userId) VALUES ('Research Associate', 99);
INSERT INTO advertisements(title, userId) VALUES ('Help Desk Technician', 73);
INSERT INTO advertisements(title, userId) VALUES ('Engineer I', 54);
INSERT INTO advertisements(title, userId) VALUES ('Professor', null);
INSERT INTO advertisements(title, userId) VALUES ('Payment Adjustment Coordinator', null);
INSERT INTO advertisements(title, userId) VALUES ('Teacher', null);
INSERT INTO advertisements(title, userId) VALUES ('Programmer I', 20);
INSERT INTO advertisements(title, userId) VALUES ('Business Systems Development Analyst', null);
INSERT INTO advertisements(title, userId) VALUES ('Software Test Engineer II', 47);
INSERT INTO advertisements(title, userId) VALUES ('Administrative Assistant III', null);
INSERT INTO advertisements(title, userId) VALUES ('Recruiting Manager', null);
INSERT INTO advertisements(title, userId) VALUES ('Paralegal', null);
INSERT INTO advertisements(title, userId) VALUES ('Physical Therapy Assistant', null);
INSERT INTO advertisements(title, userId) VALUES ('Chief Design Engineer', 80);
INSERT INTO advertisements(title, userId) VALUES ('Recruiter', 63);